import installSynApps.ViewModel.add_module_screen
import installSynApps.ViewModel.edit_individual_module
import installSynApps.ViewModel.edit_injector_screen
import installSynApps.ViewModel.edit_install_screen
import installSynApps.ViewModel.edit_macro_screen